name: readout # read by workflow
defaults:
  readout_cfg_uri: "consul-ini://{{ consul_endpoint }}/o2/components/readout/ANY/any/readout-standalone-{{ task_hostname }}"
  user: flp
  log_task_stdout: none
  log_task_stderr: none
  _module_cmdline: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load Readout Control-OCCPlugin &&
    o2-readout-exe
  # _plain_cmdline: "{{ o2_install_path }}/bin/o2-readout-exe"
  # _plain_cmdline: "sudo /usr/bin/docker run --name readout --replace --user $(id -u flp):$(id -u flp) --network=host --ipc=host -e O2_DETECTOR={{ detector }} -e O2_PARTITION={{ environment_id }} -e OCC_CONTROL_PORT=31000 -e O2_SYSTEM=FLP -e O2_ROLE=mtichak-ostack gitlab-registry.cern.ch/aliceo2group/dockerfiles/alma9-flp-node:2 /opt/o2/bin/o2-readout-exe"
  # _plain_cmdline: "sudo /usr/bin/docker run --name readout --replace --user $(id -u flp):$(id -u flp) -v /tmp:/tmp -v /etc/o2.d:/etc/o2.d --network=host --ipc=host -e O2_DETECTOR={{ detector }} -e O2_PARTITION={{ environment_id }} -e OCC_CONTROL_PORT=31000 -e O2_SYSTEM=FLP -e O2_ROLE=alio2-cr1-mvs01 gitlab-registry.cern.ch/aliceo2group/dockerfiles/alma9-flp-node:2 /opt/o2/bin/o2-readout-exe"
  # _plain_cmdline: "/usr/bin/docker run --network=host -e O2_DETECTOR={{ detector }} -e O2_PARTITION={{ environment_id }} -e OCC_CONTROL_PORT=31000 -e O2_SYSTEM=FLP -e O2_ROLE=mtichak-ostack gitlab-registry.cern.ch/aliceo2group/dockerfiles/alma8-flp-node:latest echo \"hello world\""
  # _plain_cmdline: "sudo /usr/bin/docker run --privileged --name readout --replace --user flp -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -v /tmp:/tmp -v /lib/modules/$(uname -r):/lib/modules/$(uname -r) --network=host --ipc=host -e O2_DETECTOR={{ detector }} -e O2_PARTITION={{ environment_id }} -e OCC_CONTROL_PORT=31000 -e O2_SYSTEM=FLP -e O2_ROLE=alio2-cr1-mvs01 gitlab-registry.cern.ch/aliceo2group/dockerfiles/alma9-flp-node:2 /opt/o2/bin/o2-readout-exe"
  _plain_cmdline: "sudo /usr/bin/docker run --privileged --name readout --replace --user flp -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -v /tmp:/tmp -v /lib/modules/$(uname -r):/lib/modules/$(uname -r) --network=host --ipc=host -e O2_DETECTOR -e O2_PARTITION -e OCC_CONTROL_PORT -e O2_SYSTEM -e O2_ROLE gitlab-registry.cern.ch/aliceo2group/dockerfiles/alma9-flp-node:2 /opt/o2/bin/o2-readout-exe"
control:
  mode: direct
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: readout
    type: push
    rateLogging: "{{ fmq_rate_logging }}"
    addressing: ipc
    transport: shmem
properties: {}
command: 
  stdout: "{{ log_task_stdout }}"
  stderr: "{{ log_task_stderr }}"
  shell: true
  env:
    - O2_DETECTOR={{ detector }}
    - O2_PARTITION={{ environment_id }}
  user: "{{ user }}"
  arguments:
    - "{{ readout_cfg_uri }}"
  value: "{{ len(modulepath)>0 ? _module_cmdline : _plain_cmdline }}"
